### ISSUE TITLE
OpenDOAS / DOAS and Sudo

### ISSUE THREAD

**Issue by ThisNekoGuy** [pineappleEA/Pineapple-Linux#17]
Some users prefer doas over sudo for technical reasons; can doas support be implemented for the script?

**Comment by MGThePro** [comment]
This has already been discussed internally for some weeks. We plan to release a bigger refactoring of the whole script soon, and doas support is planned to be included there.

**Comment by MGThePro** [comment]
Oh and also, for now you can use
`curl -s https://raw.githubusercontent.com/pineappleEA/Pineapple-Linux/master/pineapple.sh |  sed 's/sudo/doas/g' | sh -s --`
to have doas support before it is properly implemented and functional on either doas or sudo regardless of the command used to run it.

**Comment by ThisNekoGuy** [comment]
Cool, thanks :D

**Comment by MGThePro** [comment]
Turns out the refactoring is taking longer than expected. I added doas compatibility to the script, so the extra long command shouldn't be necessary anymore.
