### ISSUE TITLE
vk error device out of memory

### ISSUE THREAD

**Issue by Inotamira** [pineappleEA/Pineapple-Linux#5]
According to Yuzu, this was fixed on Jun 9th as seen here

https://github.com/yuzu-emu/yuzu/issues/3794

I am not even running a Beta driver, and am running the latest 450 driver. OpenGL works just fine, every Vulkan app I have besides Yuzu works just fine, and I am using the correct magic number for my card, which is 5 since I have a GTX 1080. I am using Arch.

**Comment by edisionnano** [comment]
Vulkan was never stable on yuzu, at some point it will crash. The magic number just fixes vulkan outright crashing by the time you click a game. If that's the issue, you can try some more magic numbers or the default value.
