### ISSUE TITLE
Doesn't Compile on Fedora 32

### ISSUE THREAD

**Issue by ThisNekoGuy** [pineappleEA/Pineapple-Linux#7]
After installing the dependencies listed on the readme, it still asks for a bunch of other ones (one by one) and then later fails to compile after those dependencies are installed citing that "python3-mako" is needed.

I installed that with dnf then attempted to compile again and it then soon fails citing:
![image](https://user-images.githubusercontent.com/28468662/96404419-817fad80-11a0-11eb-9da0-d702a7f10380.png)

**Comment by MGThePro** [comment]
Are you sure this is from compiling yuzu? Seems more like it's compiling mesa (which also requires python3-mako, btw)

**Comment by ThisNekoGuy** [comment]
[compileLog.log](https://github.com/pineappleEA/Pineapple-Linux/files/5404113/compileLog.log)

I nuked the `.conan` directory to try it again (thought maybe it just cached the previous attempts and something went wrong?) but it ended in a similar result about mesa again (Idk why).

**Comment by MGThePro** [comment]
This still seems to be unrelated to pineapple, none of those compile logs belong to yuzu compilation. Try clearing /tmp/pineapple, your ~/.conan folder, and clear the ccache if you use that. If that doesn't fix it I don't really know what else could be the solution
